# Generated by Django 2.2.13 on 2020-06-19 14:29

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geocontrib', '0002_auto_20200218_1343'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='ldap_project_admin_groups',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=256), blank=True, null=True, size=None, verbose_name="Groupes LDAP des contributeurs et modérateurs"),
        ),
        migrations.AddField(
            model_name='project',
            name='ldap_project_contrib_groups',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=256), blank=True, null=True, size=None, verbose_name="Groupes LDAP des administrateurs"),
        ),
    ]
