# Generated by Django 2.2.8 on 2020-07-27 09:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geocontrib', '0005_auto_20200710_1613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contextlayer',
            name='base_map',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geocontrib.BaseMap', verbose_name='Fond cartographique'),
        ),
        migrations.AlterField(
            model_name='contextlayer',
            name='layer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geocontrib.Layer', verbose_name='Couche'),
        ),
    ]
