# Generated by Django 2.2.8 on 2020-07-29 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geocontrib', '0006_auto_20200727_1147'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='contextlayer',
            unique_together=set(),
        ),
    ]
