# Generated by Django 2.2.16 on 2020-12-08 08:11

from django.db import migrations, models
import django.db.models.deletion


# def clean_deleted_feature_links(apps, schema_editor, elidible=True):
#     from django.core.management import call_command
    # call_command('data_cleansing', 'clean_feature_link')


class Migration(migrations.Migration):

    dependencies = [
        ('geocontrib', '0008_project_is_project_type'),
    ]

    operations = [
        # migrations.RunPython(clean_deleted_feature_links, elidable=True),
        migrations.AlterModelOptions(
            name='featurelink',
            options={'verbose_name': 'Liaison entre signalements', 'verbose_name_plural': 'Liaisons entre signalements'},
        ),
        migrations.AlterField(
            model_name='featurelink',
            name='feature_from',
            field=models.ForeignKey(db_column='feature_from', on_delete=django.db.models.deletion.CASCADE, related_name='feature_from', to='geocontrib.Feature', verbose_name='Signalement source'),
        ),
        migrations.AlterField(
            model_name='featurelink',
            name='feature_to',
            field=models.ForeignKey(db_column='feature_to', on_delete=django.db.models.deletion.CASCADE, related_name='feature_to', to='geocontrib.Feature', verbose_name='Signalement lié'),
        ),
    ]
