# Generated by Django 2.2.16 on 2020-12-08 08:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geocontrib', '0007_auto_20200729_0916'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='featurelink',
            options={'verbose_name': 'Liaison entre signalements', 'verbose_name_plural': 'Liaisons entre signalements'},
        ),
        migrations.AlterField(
            model_name='featurelink',
            name='feature_from',
            field=models.ForeignKey(db_column='feature_from', on_delete=django.db.models.deletion.CASCADE, related_name='feature_from', to='geocontrib.Feature', verbose_name='Signalement source'),
        ),
        migrations.AlterField(
            model_name='featurelink',
            name='feature_to',
            field=models.ForeignKey(db_column='feature_to', on_delete=django.db.models.deletion.CASCADE, related_name='feature_to', to='geocontrib.Feature', verbose_name='Signalement lié'),
        ),
    ]
