# Generated by Django 2.2.16 on 2020-11-06 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geocontrib', '0007_auto_20200729_0916'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='is_project_type',
            field=models.BooleanField(blank=True, default=False, verbose_name='Est un projet type'),
        ),
    ]
