# Generated by Django 2.2.16 on 2020-12-17 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geocontrib', '0008_project_is_project_type'),
        ('geocontrib', '0008_auto_20201208_0911'),
    ]

    operations = [
    ]
