# Generated by Django 2.2.16 on 2020-12-17 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geocontrib', '0009_merge_20201217_1725'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ('title',), 'verbose_name': 'Projet', 'verbose_name_plural': 'Projets'},
        ),
    ]
