# Generated by Django 2.2.16 on 2021-02-08 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geocontrib', '0010_auto_20201217_2112'),
    ]

    operations = [
        migrations.AddField(
            model_name='contextlayer',
            name='queryable',
            field=models.BooleanField(default=False, verbose_name='Requêtable'),
        ),
    ]
