# Generated by Django 2.2.16 on 2021-02-12 09:09

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geocontrib', '0011_contextlayer_queryable'),
    ]

    operations = [
        migrations.AddField(
            model_name='featuretype',
            name='colors_style',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name='Style Champs coloré'),
        ),
    ]
