# Generated by Django 2.2.16 on 2021-08-16 14:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import geocontrib.models.task


class Migration(migrations.Migration):

    dependencies = [
        ('geocontrib', '0012_featuretype_colors_style'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(blank=True, null=True, verbose_name='Date de création')),
                ('started_on', models.DateTimeField(blank=True, null=True, verbose_name='Date de démarrage')),
                ('finished_on', models.DateTimeField(blank=True, null=True, verbose_name='Date de fin de traîtement')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('processing', 'En cours'), ('finished', 'Terminé'), ('failed', 'Échoué')], default='pending', max_length=10, verbose_name="Status d'avancement")),
                ('geojson_file', models.FileField(blank=True, null=True, upload_to=geocontrib.models.task.ImportTask.import_path, verbose_name='Fichier Importé')),
                ('infos', models.TextField(blank=True)),
                ('feature_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geocontrib.FeatureType')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geocontrib.Project')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name_plural': "Tâches d'import",
                'verbose_name': "Tâche d'import",
            },
        ),
    ]
