# Generated by Django 2.2.24 on 2021-09-21 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geocontrib', '0013_importtask'),
    ]

    operations = [
        migrations.AddField(
            model_name='featuretype',
            name='title_optional',
            field=models.BooleanField(default=False, verbose_name='Titre optionnel'),
        ),
    ]
