# Generated by Django 2.2.16 on 2021-10-18 10:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geocontrib', '0014_featuretype_title_optional'),
    ]

    operations = [
        migrations.AddField(
            model_name='feature',
            name='last_editor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='edited_features', to=settings.AUTH_USER_MODEL, verbose_name='Dernier éditeur'),
        ),
        migrations.AlterField(
            model_name='feature',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='features', to=settings.AUTH_USER_MODEL, verbose_name='Créateur'),
        ),
    ]
