# Generated by Django 2.2.24 on 2021-12-13 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geocontrib', '0016_auto_20211104_1117'),
    ]

    operations = [
        migrations.AddField(
            model_name='featuretype',
            name='icon',
            field=models.CharField(blank=True, max_length=14, null=True, verbose_name='Icône'),
        ),
    ]
