# Generated by Django 2.2.24 on 2021-12-13 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geocontrib', '0017_featuretype_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='featuretype',
            name='icon',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Icône'),
        ),
    ]
