# Generated by Django 2.2.24 on 2022-01-07 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geocontrib', '0018_auto_20211213_1658'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='generate_share_link',
            field=models.BooleanField(default=False, verbose_name="Génération d'un lien de partage externe"),
        ),
    ]
