# Generated by Django 3.2.11 on 2022-01-21 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geocontrib', '0019_project_generate_share_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='feature',
            name='feature_data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='featuretype',
            name='colors_style',
            field=models.JSONField(blank=True, null=True, verbose_name='Style Champs coloré'),
        ),
        migrations.AlterField(
            model_name='layer',
            name='options',
            field=models.JSONField(blank=True, null=True, verbose_name='Options'),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='first name'),
        ),
    ]
