# Generated by Django 3.2.11 on 2022-03-22 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geocontrib', '0020_auto_20220121_1536'),
    ]

    operations = [
        migrations.RenameField(
            model_name='importtask',
            old_name='geojson_file',
            new_name='file',
        ),
    ]
