# Generated by Django 3.2.12 on 2022-05-19 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geocontrib', '0019_alter_user_first_name'),
        ('geocontrib', '0021_rename_geojson_file_importtask_file'),
    ]

    operations = [
    ]
