# Generated by Django 3.2.13 on 2022-05-31 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geocontrib', '0022_merge_20220519_1617'),
    ]

    operations = [
        migrations.AddField(
            model_name='featuretype',
            name='opacity',
            field=models.CharField(blank=True, max_length=3, null=True, verbose_name='Opacité'),
        ),
    ]
