# Generated by Django 3.2.13 on 2022-05-31 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geocontrib', '0023_featuretype_opacity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='featuretype',
            name='opacity',
            field=models.CharField(blank=True, max_length=4, null=True, verbose_name='Opacité'),
        ),
    ]
