# Generated by Django 3.2.13 on 2022-07-01 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geocontrib', '0024_alter_featuretype_opacity'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='fast_edition_mode',
            field=models.BooleanField(default=False, verbose_name="Mode d'édition rapide de signalements"),
        ),
    ]
