# Generated by Django 3.2.13 on 2022-07-21 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geocontrib', '0025_project_fast_edition_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='map_max_zoom_level',
            field=models.PositiveIntegerField(default=22, verbose_name='Niveau de zoom maximum de la carte'),
        ),
    ]
