# Generated by Django 3.2 on 2022-07-26 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geocontrib', '0026_project_map_max_zoom_level'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreRecordedValues',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=128, null=True, verbose_name='Nom')),
                ('values', models.JSONField(blank=True, null=True, verbose_name='Liste de valeurs pré-enregistrées')),
            ],
            options={
                'verbose_name': 'Valeur pré-enregistrée',
                'verbose_name_plural': 'Valeurs pré-enregistrées',
            },
        ),
        migrations.AlterField(
            model_name='customfield',
            name='field_type',
            field=models.CharField(choices=[('boolean', 'Booléen'), ('char', 'Chaîne de caractères'), ('date', 'Date'), ('list', 'Liste de valeurs'), ('list_pre_enr', 'Liste de valeurs pré-enregistrées'), ('integer', 'Nombre entier'), ('decimal', 'Nombre décimal'), ('text', 'Texte multiligne')], default='boolean', max_length=50, verbose_name='Type de champ'),
        ),
    ]
