# Generated by Django 3.2 on 2022-07-28 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geocontrib', '0026_project_map_max_zoom_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='customfield',
            name='is_mandatory',
            field=models.BooleanField(default=False, verbose_name='Obligatoire'),
        ),
    ]
