# Generated by Django 3.2 on 2022-07-28 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geocontrib', '0027_customfield_is_mandatory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='featuretype',
            name='geom_type',
            field=models.CharField(choices=[('linestring', 'Ligne'), ('point', 'Point'), ('polygon', 'Polygone'), ('multipolygon', 'Multipolygone'), ('multipoint', 'Multipoint'), ('multilinestring', 'Multilinestring')], default='point', max_length=50, verbose_name='Type de géométrie'),
        ),
    ]
