# Generated by Django 3.2.11 on 2022-09-05 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geocontrib', '0029_auto_20220831_1158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customfield',
            name='field_type',
            field=models.CharField(choices=[('boolean', 'Booléen'), ('char', 'Chaîne de caractères'), ('date', 'Date'), ('list', 'Liste de valeurs'), ('pre_recorded_list', 'Liste de valeurs pré-enregistrées'), ('integer', 'Nombre entier'), ('decimal', 'Nombre décimal'), ('text', 'Texte multiligne')], default='boolean', max_length=50, verbose_name='Type de champ'),
        ),
    ]
