# Generated by Django 3.2.13 on 2022-10-12 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geocontrib', '0030_alter_customfield_field_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customfield',
            name='field_type',
            field=models.CharField(choices=[('boolean', 'Booléen'), ('char', 'Chaîne de caractères'), ('date', 'Date'), ('list', 'Liste de valeurs'), ('pre_recorded_list', 'Liste de valeurs pré-enregistrées'), ('multi_choices_list', 'Liste à choix multiples'), ('integer', 'Nombre entier'), ('decimal', 'Nombre décimal'), ('text', 'Texte multiligne')], default='boolean', max_length=50, verbose_name='Type de champ'),
        ),
    ]
