# Generated by Django 3.2.13 on 2022-11-17 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geocontrib', '0031_alter_customfield_field_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customfield',
            name='label',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Label'),
        ),
    ]
