# Generated by Django 3.2.13 on 2022-12-29 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geocontrib', '0033_auto_20221222_1833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='feature_browsing_default_sort',
            field=models.CharField(default='-created_on', max_length=20, verbose_name='Tri par défaut du parcours du signalement'),
        ),
    ]
