# Generated by Django 3.2 on 2023-03-01 11:25

from django.db import migrations, models
import uuid


def force_uuid(apps, schema_editor):
    # We get the model from the versioned app registry;
    # if we directly import it, it'll be the wrong version
    User = apps.get_model('geocontrib', 'User')
    db_alias = schema_editor.connection.alias

    for instance in User.objects.using(db_alias).all():
        instance.uuid = uuid.uuid4()
        instance.save()


class Migration(migrations.Migration):

    dependencies = [
        ('geocontrib', '0035_migration_name'),
    ]

    operations = [
        # Pre generate the uuid field (nullable)
        migrations.AddField(
            model_name='user',
            name='uuid',
            field=models.UUIDField(null=True, unique=False, editable=False, verbose_name='uuid'),
        ),
        # Force uuid on existing records
        migrations.RunPython(force_uuid),
        # Recovering original settings
        migrations.AlterField(
            model_name='user',
            name='uuid',
            field=models.UUIDField(
                default=uuid.uuid4, null=False, unique=True, editable=False, verbose_name='uuid'
            ),
        ),
    ]