# Generated by Django 3.2 on 2023-03-01 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geocontrib', '0036_user_uuid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='uuid',
            new_name='token',
        ),
    ]
