# Generated by Django 3.2 on 2023-03-22 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geocontrib', '0037_rename_uuid_user_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feature',
            name='archived_on',
        ),
        migrations.AlterField(
            model_name='feature',
            name='deletion_on',
            field=models.DateField(blank=True, null=True, verbose_name='Date de suppression'),
        ),
    ]
