# Generated by Django 3.2.18 on 2023-07-03 12:39

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('geocontrib', '0038_auto_20230322_1658'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneratedToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='uuid')),
                ('username', models.CharField(max_length=150)),
                ('first_name', models.CharField(blank=True, max_length=30)),
                ('last_name', models.CharField(blank=True, max_length=150)),
                ('email', models.EmailField(blank=True, max_length=254)),
            ],
        ),
    ]
