# Generated by Django 3.2.18 on 2023-07-31 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geocontrib', '0039_customfield_conditional_field_config'),
        ('geocontrib', '0039_generatedtoken'),
    ]

    operations = [
    ]
