# Generated by Django 3.2.18 on 2023-07-27 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geocontrib', '0039_customfield_conditional_field_config'),
    ]

    operations = [
        migrations.AddField(
            model_name='customfield',
            name='forced_value_config',
            field=models.JSONField(blank=True, null=True, verbose_name='Configuration champ à valeur forcée'),
        ),
    ]
