# Generated by Django 3.2.18 on 2023-08-09 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geocontrib', '0040_merge_20230731_1138'),
    ]

    operations = [
        migrations.AddField(
            model_name='customfield',
            name='forced_value_config',
            field=models.JSONField(blank=True, null=True, verbose_name='Configuration champ à valeur forcée'),
        ),
    ]
