# Generated by Django 3.2.18 on 2023-08-28 14:38

import django.contrib.postgres.fields
from django.db import migrations, models
import geocontrib.models.feature


class Migration(migrations.Migration):

    dependencies = [
        ('geocontrib', '0041_customfield_forced_value_config'),
    ]

    operations = [
        migrations.AddField(
            model_name='featuretype',
            name='displayed_fields',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=256), blank=True, default=geocontrib.models.feature.FeatureType.get_displayed_fields_default, null=True, size=None, verbose_name='Champs conditionels à afficher'),
        ),
    ]
