# Generated by Django 3.2.18 on 2023-12-07 15:47

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geocontrib', '0043_alter_layer_schema_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feature',
            name='geom',
            field=django.contrib.gis.db.models.fields.GeometryField(blank=True, null=True, srid=4326, verbose_name='Géométrie'),
        ),
        migrations.AlterField(
            model_name='featuretype',
            name='geom_type',
            field=models.CharField(choices=[('linestring', 'Ligne'), ('point', 'Point'), ('polygon', 'Polygone'), ('multipolygon', 'Multipolygone'), ('multipoint', 'Multipoint'), ('multilinestring', 'Multilinestring'), ('none', 'Aucune')], default='point', max_length=50, verbose_name='Type de géométrie'),
        ),
    ]
