# Generated by Django 3.2.18 on 2024-01-31 16:33

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geocontrib', '0044_auto_20231207_1647'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectAttribute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=256, verbose_name='Label')),
                ('name', models.CharField(max_length=128, verbose_name='Nom')),
                ('field_type', models.CharField(choices=[('boolean', 'Booléen'), ('list', 'Liste de valeurs'), ('multi_choices_list', 'Liste à choix multiples')], default='boolean', max_length=50, verbose_name='Type de champ')),
                ('options', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=256), blank=True, null=True, size=None)),
                ('default_value', models.CharField(blank=True, max_length=50, null=True, verbose_name='Valeur par défaut')),
            ],
            options={
                'verbose_name': 'Attribut projet',
                'verbose_name_plural': 'Attributs projet',
            },
        ),
    ]
