# Generated by Django 3.2.18 on 2024-03-22 09:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geocontrib', '0044_auto_20231207_1647'),
    ]

    operations = [
        migrations.AddField(
            model_name='feature',
            name='assigned_member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_features', to=settings.AUTH_USER_MODEL, verbose_name='Membre assigné'),
        ),
        migrations.AddField(
            model_name='project',
            name='feature_assignement',
            field=models.BooleanField(default=False, verbose_name="Activation de l'assignation de signalements aux membres du projet"),
        ),
    ]
