# Generated by Django 3.2.25 on 2024-03-12 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geocontrib', '0044_auto_20231207_1647'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='archive_feature',
        ),
        migrations.RemoveField(
            model_name='project',
            name='delete_feature',
        ),
    ]
