# Generated by Django 3.2.18 on 2024-02-13 11:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geocontrib', '0045_projectattribute'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectAttributeAssociation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=256, verbose_name='Valeur')),
                ('attribute', models.ForeignKey(db_column='attribute_id', on_delete=django.db.models.deletion.CASCADE, to='geocontrib.projectattribute')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geocontrib.project')),
            ],
            options={
                'unique_together': {('project', 'attribute')},
            },
        ),
        migrations.AddField(
            model_name='project',
            name='attributes',
            field=models.ManyToManyField(through='geocontrib.ProjectAttributeAssociation', to='geocontrib.ProjectAttribute', verbose_name='Attributs'),
        ),
    ]
