# Generated by Django 3.2.25 on 2024-04-03 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geocontrib', '0045_auto_20240312_1816'),
        ('geocontrib', '0045_auto_20240322_1054'),
    ]

    operations = [
    ]
