# Generated by Django 3.2.18 on 2024-02-14 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geocontrib', '0046_auto_20240213_1224'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectattribute',
            name='default_filter_enabled',
            field=models.BooleanField(default=False, verbose_name='Activer le filtre par défaut'),
        ),
        migrations.AddField(
            model_name='projectattribute',
            name='default_filter_value',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Valeur du filtre par défaut'),
        ),
        migrations.AddField(
            model_name='projectattribute',
            name='display_filter',
            field=models.BooleanField(default=False, verbose_name='Afficher un filtre sur la liste des projets'),
        ),
    ]
