# Generated by Django 3.2.18 on 2024-03-07 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geocontrib', '0047_auto_20240214_1517'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectattribute',
            name='options',
        ),
    ]
