# Generated by Django 3.2.18 on 2024-03-07 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geocontrib', '0048_remove_projectattribute_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectattribute',
            name='options',
            field=models.JSONField(blank=True, null=True, verbose_name="Options de l'attribut"),
        ),
    ]
