# Generated by Django 3.2.18 on 2024-04-16 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geocontrib', '0050_auto_20240311_1602'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationModels',
            fields=[
                ('template_name', models.CharField(max_length=255, primary_key=True, serialize=False, verbose_name='Nom du modèle de notification')),
                ('subject', models.CharField(blank=True, max_length=255, null=True, verbose_name='Objet')),
                ('message', models.TextField(blank=True, null=True, verbose_name='Corps du message')),
                ('notification_type', models.CharField(choices=[('global', 'Globale'), ('per_project', 'Par projet')], default='global', max_length=50, verbose_name='Type de notification')),
            ],
            options={
                'verbose_name': 'Modèle de notifications',
                'verbose_name_plural': 'Modèles de notifications',
            },
        ),
    ]
