# Generated by Django 3.2.18 on 2024-05-27 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geocontrib', '0052_auto_20240524_1224'),
    ]

    operations = [
        migrations.AddField(
            model_name='stackedevent',
            name='only_key_document',
            field=models.BooleanField(default=False, verbose_name='Document clé uniquement'),
        ),
    ]
