# Generated by Django 3.2.18 on 2024-06-13 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geocontrib', '0053_load_new_data_notif_beat'),
    ]

    operations = [
        migrations.AddField(
            model_name='featuretype',
            name='disable_notification',
            field=models.BooleanField(default=False, verbose_name='Désactiver les notifications'),
        ),
    ]
