# Generated by Django 3.2.18 on 2024-07-29 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geocontrib', '0054_featuretype_disable_notification'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customfield',
            options={'ordering': ['position'], 'verbose_name': 'Champ personnalisé', 'verbose_name_plural': 'Champs personnalisés'},
        ),
    ]
