# Generated by Django 3.2.18 on 2024-09-19 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geocontrib', '0045_auto_20240322_1054'),
        ('geocontrib', '0055_alter_customfield_options'),
    ]

    operations = [
    ]
