# Generated by Django 4.2 on 2025-03-12 15:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import geocontrib.models.user


class Migration(migrations.Migration):

    dependencies = [
        ('geocontrib', '0057_generate_views_for_existing_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsersGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codename', models.CharField(max_length=255, unique=True, validators=[geocontrib.models.user.validate_codename], verbose_name='Nom (identifiant)')),
                ('display_name', models.CharField(max_length=255, verbose_name='Nom affiché')),
                ('usergroup_type', models.CharField(max_length=255, verbose_name='Type de groupe utilisateurs')),
                ('is_global', models.BooleanField(default=False, verbose_name="Groupe 'all'")),
            ],
            options={
                'verbose_name': "Groupe d'utilisateurs",
                'verbose_name_plural': "Groupes d'utilisateurs",
            },
        ),
        migrations.AlterField(
            model_name='customfield',
            name='field_type',
            field=models.CharField(choices=[('boolean', 'Booléen'), ('char', 'Chaîne de caractères'), ('date', 'Date'), ('list', 'Liste de valeurs'), ('pre_recorded_list', 'Liste de valeurs pré-enregistrées'), ('multi_choices_list', 'Liste à choix multiples'), ('integer', 'Nombre entier'), ('decimal', 'Nombre décimal'), ('text', 'Texte multiligne'), ('notif_group', 'Notification à un groupe')], default='boolean', max_length=50, verbose_name='Type de champ'),
        ),
        migrations.CreateModel(
            name='UserGroupMembership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_at', models.DateTimeField(auto_now_add=True, verbose_name="Date d'adhésion")),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geocontrib.usersgroup')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Membre du groupe',
                'verbose_name_plural': 'Membres des groupes',
                'unique_together': {('user', 'group')},
            },
        ),
    ]
