# Generated by Django 4.2 on 2025-09-26 15:50

from django.db import migrations

def create_unaccent_extension(apps, schema_editor):
    schema_editor.execute("CREATE EXTENSION IF NOT EXISTS unaccent;")

class Migration(migrations.Migration):

    dependencies = [
        ('geocontrib', '0060_load_new_data_usercreation_notif'),
    ]

    operations = [
        migrations.RunPython(create_unaccent_extension),
    ]
