# Generated by Django 4.2 on 2025-10-31 17:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geocontrib', '0061_auto_20250926_1750'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='notified_members_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='notified_members_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects_notified', to=settings.AUTH_USER_MODEL),
        ),
    ]
