# Generated by Django 4.2 on 2025-11-21 17:15

from django.db import migrations
from django.core.management import call_command

def load_datas(apps, schema_editor):
    """
    This migration is designed to ensure that updated data for notification settings
    and scheduled tasks are loaded into the database during deployments.
    It's necessary for environments where the application is already installed
    and needs these data updates to function correctly without requiring a manual reload.
    The `elidable=True` parameter ensures that this migration can be skipped during operations
    like applying migrations with `--fake`, making it suitable for environments that are being updated rather than freshly installed.
    """
    call_command('loaddata', 'geocontrib/data/perm.json')

def reverse_load_datas(apps, schema_editor):
    # pour permettre de revenir en arrière dans les migrations sans utiliser --fake
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('geocontrib', '0063_load_project_member_notification_template'),
    ]

    operations = [
        migrations.RunPython(
            load_datas,
            reverse_code=reverse_load_datas,
            elidable=True
        ),
    ]
