sonar.sources = geocontrib/, api/, plugin_georchestra/
sonar.exclusions = **/*test*, geocontrib/api/doc_swagger/**, geocontrib/static/**, geocontrib/migrations/**, docs/**, api/tests/**
#sonar.tests = api/tests/
