# Generated by Django 2.2 on 2019-08-05 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collab', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stackedevent',
            name='project_slug',
            field=models.SlugField(blank=True, max_length=256, null=True, verbose_name='Slug du projet'),
        ),
        migrations.AlterField(
            model_name='customfield',
            name='field_type',
            field=models.CharField(choices=[('boolean', 'Booléen'), ('char', 'Chaîne de caractères'), ('date', 'Date'), ('integer', 'Entier'), ('decimal', 'Décimale'), ('text', 'Champ texte')], default='boolean', max_length=50, verbose_name='Type de champ'),
        ),
    ]
