# Generated by Django 2.2 on 2019-08-06 14:30

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collab', '0002_auto_20190805_1519'),
    ]

    operations = [
        migrations.AddField(
            model_name='customfield',
            name='options',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=256), blank=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='customfield',
            name='field_type',
            field=models.CharField(choices=[('boolean', 'Booléen'), ('char', 'Chaîne de caractères'), ('date', 'Date'), ('integer', 'Entier'), ('decimal', 'Décimale'), ('text', 'Champ texte'), ('list', 'Liste')], default='boolean', max_length=50, verbose_name='Type de champ'),
        ),
    ]
