# Generated by Django 2.2 on 2019-07-19 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collab', '0002_auto_20190718_1351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='archive_feature',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Délai avant archivage'),
        ),
        migrations.AlterField(
            model_name='project',
            name='delete_feature',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Délai avant suppression'),
        ),
    ]
