# Generated by Django 2.2 on 2019-07-22 05:37

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collab', '0003_auto_20190719_0955'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attachment',
            options={'verbose_name': 'Pièce jointe', 'verbose_name_plural': 'Pièces jointes'},
        ),
        migrations.AlterModelOptions(
            name='customfield',
            options={'verbose_name': 'Champ personnalisé', 'verbose_name_plural': 'Champs personnalisés'},
        ),
        migrations.AlterModelOptions(
            name='featuretype',
            options={'verbose_name': 'Type de signalement', 'verbose_name_plural': 'Types de signalements'},
        ),
        migrations.AlterModelOptions(
            name='stackedevent',
            options={'verbose_name': 'Lot de notifications', 'verbose_name_plural': 'Lots de notifications des abonnées'},
        ),
        migrations.AlterField(
            model_name='customfield',
            name='field_type',
            field=models.CharField(blank=True, choices=[('boolean', 'Booléen'), ('char', 'Chaîne de caractères'), ('date', 'Date'), ('integer', 'Entier'), ('decimal', 'Décimale'), ('text', 'Champ texte')], default='boolean', max_length=50, null=True, verbose_name='Type de champ'),
        ),
        migrations.AlterField(
            model_name='event',
            name='feature_type_slug',
            field=models.SlugField(blank=True, max_length=256, null=True, verbose_name='Slug du type de signalement'),
        ),
        migrations.AlterField(
            model_name='event',
            name='project_slug',
            field=models.SlugField(blank=True, max_length=256, null=True, verbose_name='Slug du projet'),
        ),
        migrations.AlterField(
            model_name='feature',
            name='geom',
            field=django.contrib.gis.db.models.fields.GeometryField(blank=True, null=True, srid=4326, verbose_name='Géométrie'),
        ),
        migrations.AlterField(
            model_name='feature',
            name='status',
            field=models.CharField(blank=True, choices=[('draft', 'Brouillon'), ('pending', 'En attente de publication'), ('published', 'Publié'), ('archived', 'Archivé')], default='draft', max_length=50, null=True, verbose_name='Statut'),
        ),
        migrations.AlterField(
            model_name='featuretype',
            name='geom_type',
            field=models.CharField(choices=[('linestring', 'Ligne'), ('point', 'Point'), ('polygon', 'Polygone')], default='boolean', max_length=50, verbose_name='Type de géométrie'),
        ),
        migrations.AlterField(
            model_name='stackedevent',
            name='updated_on',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date de dernière modification du lot'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='created_on',
            field=models.DateTimeField(blank=True, null=True, verbose_name="Date de création de l'abonnement"),
        ),
    ]
