# Generated by Django 2.2 on 2019-07-10 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collab', '0003_auto_20190709_1351'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='customfield',
            unique_together={('name', 'feature_type')},
        ),
    ]
