# Generated by Django 2.2 on 2019-07-19 15:19

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collab', '0003_auto_20190719_0955'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomFieldInterface',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_type', models.CharField(blank=True, choices=[('unique', 'Entrée unique'), ('multi_choice', 'Choix multiple'), ('radio', 'Bouton radio'), ('range', 'Curseur')], default='unique', max_length=50, null=True, verbose_name='Type de champs')),
                ('options', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=256), blank=True, size=None)),
            ],
            options={
                'verbose_name': 'Interface de champs personnalisés',
                'verbose_name_plural': 'Interfaces de champs personnalisés',
            },
        ),
    ]
