# Generated by Django 2.2 on 2019-08-06 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collab', '0003_auto_20190806_1430'),
    ]

    operations = [
        migrations.AddField(
            model_name='layer',
            name='attribution',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Attribution'),
        ),
    ]
