# Generated by Django 2.2 on 2019-08-06 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collab', '0004_layer_attribution'),
    ]

    operations = [
        migrations.AlterField(
            model_name='layer',
            name='service',
            field=models.CharField(max_length=256, verbose_name='Service'),
        ),
    ]
