# Generated by Django 2.2 on 2019-07-22 08:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('collab', '0004_auto_20190722_0537'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='features_info',
        ),
        migrations.AlterField(
            model_name='featuretype',
            name='slug',
            field=models.SlugField(editable=False, max_length=256, null=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='project',
            name='slug',
            field=models.SlugField(editable=False, max_length=256, null=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='project',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Auteur'),
        ),
    ]
