# Generated by Django 2.2 on 2019-08-07 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collab', '0005_auto_20190806_1622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.CharField(choices=[('create', 'Création'), ('update', 'Modification'), ('archive', 'Archivage'), ('delete', 'Suppression')], max_length=100, verbose_name="Type de l'évènement"),
        ),
    ]
