# Generated by Django 2.2 on 2019-08-07 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collab', '0006_auto_20190807_0723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlevelpermission',
            name='user_type_id',
            field=models.CharField(choices=[('anonymous', 'Utilisateur anonyme'), ('logged_user', 'Utilisateur connecté'), ('contributor', 'Contributeur'), ('moderator', 'Modérateur'), ('admin', 'Administrateur projet')], max_length=100, primary_key=True, serialize=False, verbose_name='Identifiant'),
        ),
    ]
