# Generated by Django 2.2 on 2019-07-22 14:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('collab', '0006_auto_20190722_1208'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='feature_id',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='project_slug',
        ),
        migrations.AddField(
            model_name='subscription',
            name='feature',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='collab.Feature'),
        ),
    ]
