# Generated by Django 2.2 on 2019-08-07 10:06

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collab', '0007_auto_20190807_0745'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='layer',
            name='attribution',
        ),
        migrations.RemoveField(
            model_name='layer',
            name='name',
        ),
        migrations.RemoveField(
            model_name='layer',
            name='style',
        ),
        migrations.AddField(
            model_name='layer',
            name='options',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name='Options'),
        ),
    ]
