# Generated by Django 2.2 on 2019-08-08 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collab', '0008_auto_20190807_1206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customfield',
            name='field_type',
            field=models.CharField(choices=[('boolean', 'Booléen'), ('char', 'Chaîne de caractères'), ('date', 'Date'), ('list', 'Liste de valeurs'), ('integer', 'Nombre entier'), ('decimal', 'Nombre décimal'), ('text', 'Texte multiligne')], default='boolean', max_length=50, verbose_name='Type de champ'),
        ),
    ]
