# Generated by Django 2.2 on 2019-07-24 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collab', '0008_auto_20190723_1316'),
    ]

    operations = [
        migrations.AddField(
            model_name='featuretype',
            name='color',
            field=models.CharField(blank=True, max_length=7, null=True, verbose_name='Couleur'),
        ),
        migrations.AddField(
            model_name='project',
            name='updated_on',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date de modification'),
        ),
        migrations.AlterField(
            model_name='featuretype',
            name='geom_type',
            field=models.CharField(choices=[('linestring', 'Ligne'), ('point', 'Point'), ('polygon', 'Polygone')], default='point', max_length=50, verbose_name='Type de géométrie'),
        ),
    ]
