# Generated by Django 2.2 on 2019-07-30 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collab', '0009_auto_20190724_0811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.CharField(choices=[('create', 'Création'), ('update', 'Modification'), ('delete', 'Suppression')], max_length=100, verbose_name="Type de l'évènement"),
        ),
        migrations.AlterField(
            model_name='event',
            name='project_slug',
            field=models.SlugField(max_length=256, verbose_name='Slug du projet'),
        ),
        migrations.AlterField(
            model_name='stackedevent',
            name='sending_frequency',
            field=models.CharField(blank=True, choices=[('never', 'Jamais'), ('instantly', 'Instantanément'), ('daily', 'Quotidienne'), ('weekly', 'Hebdomadaire')], default='daily', max_length=20, null=True, verbose_name='Fréquence de notification'),
        ),
    ]
