# Generated by Django 2.2 on 2019-08-09 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collab', '0009_auto_20190808_1353'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='authorization',
            options={'verbose_name': 'Autorisation'},
        ),
        migrations.AlterModelOptions(
            name='layer',
            options={'ordering': ['project', 'order'], 'verbose_name': 'Couche', 'verbose_name_plural': 'Couches'},
        ),
        migrations.AlterUniqueTogether(
            name='layer',
            unique_together=set(),
        ),
    ]
