# Generated by Django 2.2 on 2019-07-30 10:32

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collab', '0010_auto_20190730_0813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feature',
            name='geom',
            field=django.contrib.gis.db.models.fields.GeometryField(srid=4326, verbose_name='Géométrie'),
        ),
        migrations.AlterField(
            model_name='feature',
            name='status',
            field=models.CharField(choices=[('draft', 'Brouillon'), ('pending', 'En attente de publication'), ('published', 'Publié'), ('archived', 'Archivé')], default='draft', max_length=50, verbose_name='Statut'),
        ),
    ]
