# Generated by Django 2.2 on 2019-08-02 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collab', '0011_auto_20190730_1032'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attachment',
            old_name='type_objet',
            new_name='object_type',
        ),
    ]
