#!/bin/bash
# --------------------------------------------------------------- #
create_link()
{
    ln -s $1 $2 2> /dev/null
    if [ $? -eq 0 ]; then
        echo "[  OK  ] Link created: ${1}->${2}"
    else
        echo "[FAILED] No such file or directory: ${1}"
        exit 1
    fi
}
# --------------------------------------------------------------- #
echo "Step 01."
cd $APP_PATH/
marker_file="marker_file_step_01"
if [ -f $marker_file ]; then
    echo "$marker_file already exists"
else
    echo "$marker_file does not exist"
    django-admin startproject config .

    create_link src/geocontrib/ .
    create_link src/api/ .
    create_link src/plugin_georchestra/ .

    # Preparation spécifique
    # Django
    if [ -f "config/urls.py" ]; then
        rm config/urls.py
    fi
    if [ -f "config/settings.py" ]; then
        rm config/settings.py
    fi
    cp src/docker/geocontrib/settings.py config/settings.py
    cp src/docker/geocontrib/urls.py config/urls.py
    cp src/config_sample/celery.py src/config_sample/__init__.py config/

    # Attente du serveur postgres
    echo "Waiting for database..."
    i=1
    while true
    do
        if  $(nc -z ${DB_HOST} 5432) ; then
            echo "[${DB_HOST}] The database server is ready."
            break
        fi
        echo "[Retry: $i] The database server is not ready. Next attempt in ${TIME_SLEEP}s"
        sleep $TIME_SLEEP
        ((i++))
    done

    python manage.py migrate
    python manage.py shell -c "from django.contrib.auth import get_user_model; User= get_user_model(); User.objects.create_superuser('$APP_ADMIN_USER', '$APP_ADMIN_EMAIL', '$APP_ADMIN_PWD')"
    python manage.py loaddata src/geocontrib/data/perm.json

    # Check if flatpages exists before loading flatpages.json
    num_flatpages=`python manage.py shell --command="from django.contrib.flatpages.models import FlatPage; print(len(FlatPage.objects.all()))"`
    if [ $num_flatpages -eq 0 ]; then
        # if the number of flatpages is 0, then we load the data file
        python manage.py loaddata src/geocontrib/data/flatpages.json
    fi

    echo "Ok" > $marker_file
fi

echo "$(basename $0) complete."
